---
- name: Deploy bus_time_alert to Raspberry Pi
  hosts: penelopi.local
  remote_user: pi
  tasks:
    - name: Install system level dependencies
      become: true
      apt:
        name: "{{ item }}"
        update_cache: true
      with_items:
          - python3
          - python3-pip
    - name: Copy source code
      copy:
        src: ../bus_time_alert
        dest: /home/pi
    - name: Install bus_time_alert Python 3 dependencies
      become: true
      pip:
        executable: pip3
        requirements: /home/pi/bus_time_alert/requirements.txt
    - name: Add config file for 126 Racine and Jackson bus stop
      template:
        src: templates/126-racine-and-jackson.json.j2
        dest: /home/pi/bus_time_alert/126-racine-and-jackson.json
    - name: Copy systemd config for 126 Racine and Jackson bus stop
      become: true
      copy:
        src: files/bta_126_racine_jackson.service
        dest: /etc/systemd/system/bta_126_racine_jackson.service
    - name: Bounce systemd service for 126 Racine and Jackson bus stop
      become: true
      systemd:
        name: bta_126_racine_jackson
        enabled: yes
        daemon_reload: yes
        state: restarted
