---
- name: Create AWS resources
  hosts: localhost
  connection: local
  vars_files:
      - host_vars/penelopi.local
  tasks:
    - name: CloudFormation stack
      cloudformation:
        stack_name: BusTimeAlert
        state: present
        region: us-east-1
        template: templates/cloudformation.yaml.j2
        template_parameters:
            S3BucketName: "{{ aws_s3_bucket_name }}"
      register: aws_result
- name: Deploy bus_time_alert to Raspberry Pi
  hosts: penelopi.local
  remote_user: pi
  vars_files:
      - group_vars/bus_stops.yaml
  tasks:
    - name: Install system level dependencies
      become: true
      apt:
        name: "{{ item }}"
        update_cache: true
      with_items:
          - python3
          - python3-pip
    - name: Copy source code
      copy:
        src: ../bus_time_alert
        dest: /home/pi
    - name: Install bus_time_alert Python 3 dependencies
      become: true
      pip:
        executable: pip3
        requirements: /home/pi/bus_time_alert/requirements.txt
    - name: Add config files for bus stops
      template:
        src: templates/config.json.j2
        dest: "/home/pi/bus_time_alert/{{ item.name }}.json"
      with_items: "{{ bus_stops }}"
    - name: Add led_server.py
      template:
        src: templates/led_server.py.j2
        dest: "/home/pi/bus_time_alert/led_server_{{ item.name }}.py"
      with_items: "{{ bus_stops }}"
    - name: Copy systemd config files
      become: true
      template:
        src: templates/systemd.service.j2
        dest: "/etc/systemd/system/bta_{{ item.name }}.service"
      with_items: "{{ bus_stops }}"
    - name: Bounce systemd services
      become: true
      systemd:
        name: "bta_{{ item.name }}"
        enabled: yes
        daemon_reload: yes
        state: restarted
      with_items: "{{ bus_stops }}"
