---
- name: "Deploy bus_time_alert to Raspberry Pi"
  hosts: penelopi.local
  remote_user: pi
  become: true
  tasks:
    - name: "Upgrade all packages to the latest version"
      apt:
          name: "*"
          state: latest
    - name: "Install Python 3"
      apt:
          name: python3
    - name: "Install Pip 3"
      apt:
          name: python3-pip
  - name: "Install bus_time_alert Python packages"
    pip:
        executable: pip3
        requirements: /home/pi/bus_time_alert/requirements.txt
    - name: "Add config file for 126 Racine and Jackson bus stop"
      template:
          src: templates/126-racine-and-jackson.json.j2
          dest: /home/pi/bus_time_alert/126-racine-and-jackson.json
